const https = require('https');

const loginData = JSON.stringify({
    email: 'admin@medfinance360.com',
    password: 'Admin@123',
    hospitalType: ''
});

const req = https.request('https://medfinance-production.up.railway.app/api/auth/login', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Content-Length': loginData.length
    }
}, (res) => {
    let data = '';
    res.on('data', chunk => data += chunk);
    res.on('end', () => {
        const result = JSON.parse(data);
        if (!result.token) {
            console.error('Login Failed:', result);
            return;
        }
        
        console.log('Login Success. Creating File Request...');
        
        const requestData = JSON.stringify({
            patientId: 104, // Using the TESTACTIVITY LOGUSER we created earlier
            requestType: 'retrieval',
            urgency: 'urgent',
            notes: 'Test file request generated by automated testing script.'
        });

        const createReq = https.request('https://medfinance-production.up.railway.app/api/records/requests', {
            method: 'POST',
            headers: { 
                'Authorization': 'Bearer ' + result.token,
                'Content-Type': 'application/json',
                'Content-Length': requestData.length
            }
        }, (res2) => {
            let data2 = '';
            res2.on('data', chunk => data2 += chunk);
            res2.on('end', () => {
                console.log('Create Request Response:', res2.statusCode);
                console.log(data2);
            });
        });
        
        createReq.on('error', console.error);
        createReq.write(requestData);
        createReq.end();
    });
});

req.on('error', console.error);
req.write(loginData);
req.end();
