import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Printer, Eye, FileText, CheckCircle, Clock } from 'lucide-react';
import api from '../../services/apiClient';

const SchemeInvoices = ({ schemeId }) => {
    const navigate = useNavigate();
    const [invoices, setInvoices] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showModal, setShowModal] = useState(false);
    const [generateForm, setGenerateForm] = useState({
        month: new Date().getMonth() + 1, // Current month (1-12)
        year: new Date().getFullYear()
    });
    const [generating, setGenerating] = useState(false);
    const [error, setError] = useState(null);

    useEffect(() => {
        if (schemeId) {
            fetchInvoices();
        }
    }, [schemeId]);

    const fetchInvoices = async () => {
        try {
            setLoading(true);
            const response = await api.get(`/receivables/schemes/${schemeId}/invoices`);
            setInvoices(response.data);
        } catch (error) {
            console.error('Error fetching invoices:', error);
        } finally {
            setLoading(false);
        }
    };

    const handleGenerate = async (e) => {
        e.preventDefault();
        try {
            setGenerating(true);
            setError(null);
            const response = await api.post('/receivables/schemes/invoices/generate', {
                schemeId,
                month: Number(generateForm.month),
                year: Number(generateForm.year)
            });
            setShowModal(false);
            fetchInvoices();
            // Navigate to the newly created invoice
            navigate(`/app/receivables/invoices/${response.data.id}`);
        } catch (error) {
            console.error('Error generating invoice:', error);
            setError(error.response?.data?.error || 'Failed to generate invoice');
        } finally {
            setGenerating(false);
        }
    };

    const getStatusBadge = (status) => {
        const colors = {
            draft: 'bg-yellow-100 text-yellow-800',
            final: 'bg-blue-100 text-blue-800',
            sent: 'bg-purple-100 text-purple-800',
            paid: 'bg-green-100 text-green-800',
            cancelled: 'bg-red-100 text-red-800'
        };
        return `px-2 py-0.5 rounded text-xs font-medium uppercase ${colors[status] || 'bg-gray-100 text-gray-800'}`;
    };

    return (
        <div className="bg-black/40 rounded-[3rem] shadow-2xl border border-white/5 overflow-hidden backdrop-blur-sm">
            {/* Header */}
            <div className="p-8 border-b border-white/5 flex justify-between items-center bg-white/[0.02]">
                <h3 className="font-black text-white uppercase tracking-tighter">Monthly Invoices</h3>
                <button
                    onClick={() => setShowModal(true)}
                    className="flex items-center gap-2 px-6 py-2.5 bg-gradient-to-r from-primary to-primary/80 hover:scale-105 active:scale-95 text-white rounded-full text-[10px] font-black uppercase tracking-widest transition-all shadow-[0_0_20px_rgba(255,0,204,0.3)]"
                >
                    <Plus className="w-4 h-4" />
                    Generate Invoice
                </button>
            </div>

            {/* List */}
            <div className="overflow-x-auto custom-scrollbar">
                <table className="w-full text-sm text-left">
                    <thead className="text-[10px] text-white/40 uppercase font-black tracking-widest bg-white/[0.03] border-b border-white/5">
                        <tr>
                            <th className="px-8 py-5">Invoice #</th>
                            <th className="px-8 py-5">Period</th>
                            <th className="px-8 py-5 text-right">Amount</th>
                            <th className="px-8 py-5">Status</th>
                            <th className="px-8 py-5">Generated By</th>
                            <th className="px-8 py-5 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-white/5">
                        {loading ? (
                            <tr><td colSpan="6" className="p-8 text-center text-gray-500">Loading invoices...</td></tr>
                        ) : invoices.length === 0 ? (
                            <tr><td colSpan="6" className="p-8 text-center text-gray-500">No invoices generated yet.</td></tr>
                        ) : (
                            invoices.map((inv) => (
                                <tr key={inv.id} className="hover:bg-white/[0.02] transition-colors group text-white/70">
                                    <td className="px-8 py-5 font-mono text-primary font-bold tracking-tight">{inv.invoiceNumber}</td>
                                    <td className="px-8 py-5 text-white/60 font-medium">
                                        {new Date(inv.periodStart).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })}
                                    </td>
                                    <td className="px-8 py-5 text-right font-black text-white tabular-nums">
                                        {Number(inv.totalAmount).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                                    </td>
                                    <td className="px-8 py-5">
                                        <span className={getStatusBadge(inv.status)}>{inv.status}</span>
                                    </td>
                                    <td className="px-8 py-5 text-white/30 text-[10px] font-black uppercase tracking-widest">
                                        User #{inv.generatedBy}
                                    </td>
                                    <td className="px-8 py-5 text-right">
                                        <button
                                            onClick={() => navigate(`/app/receivables/invoices/${inv.id}`)}
                                            className="p-3 hover:bg-white/5 text-white/40 hover:text-white rounded-2xl transition-all"
                                            title="View Details"
                                        >
                                            <Eye className="w-5 h-5" />
                                        </button>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>

            {/* Generate Modal */}
            {showModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md animate-fade-in">
                    <div className="bg-bg-secondary border border-white/10 rounded-[4rem] shadow-[0_32px_120px_rgba(0,0,0,0.8)] w-full max-w-lg overflow-hidden flex flex-col scale-100 p-2">
                        <div className="p-12">
                            <h3 className="text-4xl font-black text-white mb-2 uppercase tracking-tighter">GENERATE INVOICE</h3>
                            <p className="text-white/40 text-xs font-black uppercase tracking-widest mb-10">Select billing period</p>

                            {error && (
                                <div className="mb-4 p-3 bg-red-50 text-red-700 text-sm rounded border border-red-200">
                                    {error}
                                </div>
                            )}

                            <form onSubmit={handleGenerate} className="space-y-8">
                                <div className="grid grid-cols-2 gap-6">
                                    <div className="space-y-3">
                                        <label className="block text-[10px] font-black text-white/40 uppercase tracking-[0.2em] ml-2">Month</label>
                                        <select
                                            value={generateForm.month}
                                            onChange={(e) => setGenerateForm({ ...generateForm, month: e.target.value })}
                                            className="w-full bg-white/5 border border-white/10 rounded-3xl px-6 py-4 text-sm font-bold text-white focus:ring-2 focus:ring-primary/20 appearance-none cursor-pointer hover:bg-white/10 transition-all uppercase tracking-widest"
                                            required
                                        >
                                            {Array.from({ length: 12 }, (_, i) => (
                                                <option key={i + 1} value={i + 1} className="bg-bg-primary">
                                                    {new Date(0, i).toLocaleString('default', { month: 'long' })}
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                    <div className="space-y-3">
                                        <label className="block text-[10px] font-black text-white/40 uppercase tracking-[0.2em] ml-2">Year</label>
                                        <input
                                            type="number"
                                            value={generateForm.year}
                                            onChange={(e) => setGenerateForm({ ...generateForm, year: e.target.value })}
                                            className="w-full bg-white/5 border border-white/10 rounded-3xl px-6 py-4 text-sm font-bold text-white focus:ring-2 focus:ring-primary/20 hover:bg-white/10 transition-all"
                                            min="2020"
                                            max="2030"
                                            required
                                        />
                                    </div>
                                </div>

                                <div className="flex justify-end gap-4 pt-6">
                                    <button
                                        type="button"
                                        onClick={() => setShowModal(false)}
                                        className="px-8 py-4 bg-white/5 hover:bg-white/10 text-white/60 hover:text-white rounded-3xl text-[10px] font-black uppercase tracking-widest transition-all"
                                        disabled={generating}
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        type="submit"
                                        className="px-8 py-4 bg-gradient-to-r from-primary to-primary/80 hover:scale-105 active:scale-95 text-white rounded-3xl text-[10px] font-black uppercase tracking-widest transition-all shadow-[0_20px_40px_rgba(255,0,204,0.2)]"
                                        disabled={generating}
                                    >
                                        {generating ? 'GENERATING...' : 'GENERATE INVOICE'}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default SchemeInvoices;
