import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Printer, Eye, FileText, CheckCircle, Clock } from 'lucide-react';
import api from '../../services/apiClient';

const SchemeInvoices = ({ schemeId }) => {
    const navigate = useNavigate();
    const [invoices, setInvoices] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showModal, setShowModal] = useState(false);
    const [generateForm, setGenerateForm] = useState({
        month: new Date().getMonth() + 1, // Current month (1-12)
        year: new Date().getFullYear()
    });
    const [generating, setGenerating] = useState(false);
    const [error, setError] = useState(null);

    useEffect(() => {
        if (schemeId) {
            fetchInvoices();
        }
    }, [schemeId]);

    const fetchInvoices = async () => {
        try {
            setLoading(true);
            const response = await api.get(`/receivables/schemes/${schemeId}/invoices`);
            setInvoices(response.data);
        } catch (error) {
            console.error('Error fetching invoices:', error);
        } finally {
            setLoading(false);
        }
    };

    const handleGenerate = async (e) => {
        e.preventDefault();
        try {
            setGenerating(true);
            setError(null);
            const response = await api.post('/receivables/schemes/invoices/generate', {
                schemeId,
                month: Number(generateForm.month),
                year: Number(generateForm.year)
            });
            setShowModal(false);
            fetchInvoices();
            // Navigate to the newly created invoice
            navigate(`/app/receivables/invoices/${response.data.id}`);
        } catch (error) {
            console.error('Error generating invoice:', error);
            setError(error.response?.data?.error || 'Failed to generate invoice');
        } finally {
            setGenerating(false);
        }
    };

    const getStatusBadge = (status) => {
        const colors = {
            draft: 'bg-yellow-100 text-yellow-800',
            final: 'bg-blue-100 text-blue-800',
            sent: 'bg-purple-100 text-purple-800',
            paid: 'bg-green-100 text-green-800',
            cancelled: 'bg-red-100 text-red-800'
        };
        return `px-2 py-0.5 rounded text-xs font-medium uppercase ${colors[status] || 'bg-gray-100 text-gray-800'}`;
    };

    return (
        <div className="bg-white rounded-lg shadow-sm border border-gray-200">
            {/* Header */}
            <div className="p-4 border-b border-gray-200 flex justify-between items-center">
                <h3 className="font-semibold text-gray-700">Monthly Invoices</h3>
                <button
                    onClick={() => setShowModal(true)}
                    className="btn btn-primary btn-sm flex items-center gap-2"
                >
                    <Plus className="w-4 h-4" />
                    Generate Invoice
                </button>
            </div>

            {/* List */}
            <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                    <thead className="text-xs text-gray-500 uppercase bg-gray-50 border-b border-gray-200">
                        <tr>
                            <th className="px-4 py-3">Invoice #</th>
                            <th className="px-4 py-3">Period</th>
                            <th className="px-4 py-3 text-right">Amount</th>
                            <th className="px-4 py-3">Status</th>
                            <th className="px-4 py-3">Generated By</th>
                            <th className="px-4 py-3 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {loading ? (
                            <tr><td colSpan="6" className="p-8 text-center text-gray-500">Loading invoices...</td></tr>
                        ) : invoices.length === 0 ? (
                            <tr><td colSpan="6" className="p-8 text-center text-gray-500">No invoices generated yet.</td></tr>
                        ) : (
                            invoices.map((inv) => (
                                <tr key={inv.id} className="hover:bg-gray-50">
                                    <td className="px-4 py-3 font-mono text-primary-600 font-medium">{inv.invoiceNumber}</td>
                                    <td className="px-4 py-3 text-gray-600">
                                        {new Date(inv.periodStart).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })}
                                    </td>
                                    <td className="px-4 py-3 text-right font-bold text-gray-900">
                                        {Number(inv.totalAmount).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                                    </td>
                                    <td className="px-4 py-3">
                                        <span className={getStatusBadge(inv.status)}>{inv.status}</span>
                                    </td>
                                    <td className="px-4 py-3 text-gray-500 text-xs">
                                        User #{inv.generatedBy}
                                    </td>
                                    <td className="px-4 py-3 text-right">
                                        <button
                                            onClick={() => navigate(`/app/receivables/invoices/${inv.id}`)}
                                            className="p-1 hover:bg-gray-100 text-gray-600 rounded transition-colors"
                                            title="View Details"
                                        >
                                            <Eye className="w-4 h-4" />
                                        </button>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>

            {/* Generate Modal */}
            {showModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
                    <div className="bg-white rounded-lg shadow-xl w-full max-w-md p-6">
                        <h3 className="text-lg font-bold text-gray-900 mb-4">Generate Monthly Invoice</h3>

                        {error && (
                            <div className="mb-4 p-3 bg-red-50 text-red-700 text-sm rounded border border-red-200">
                                {error}
                            </div>
                        )}

                        <form onSubmit={handleGenerate}>
                            <div className="grid grid-cols-2 gap-4 mb-6">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Month</label>
                                    <select
                                        value={generateForm.month}
                                        onChange={(e) => setGenerateForm({ ...generateForm, month: e.target.value })}
                                        className="form-select w-full"
                                        required
                                    >
                                        {Array.from({ length: 12 }, (_, i) => (
                                            <option key={i + 1} value={i + 1}>
                                                {new Date(0, i).toLocaleString('default', { month: 'long' })}
                                            </option>
                                        ))}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Year</label>
                                    <input
                                        type="number"
                                        value={generateForm.year}
                                        onChange={(e) => setGenerateForm({ ...generateForm, year: e.target.value })}
                                        className="form-input w-full"
                                        min="2020"
                                        max="2030"
                                        required
                                    />
                                </div>
                            </div>

                            <div className="flex justify-end gap-3">
                                <button
                                    type="button"
                                    onClick={() => setShowModal(false)}
                                    className="btn btn-secondary"
                                    disabled={generating}
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="btn btn-primary"
                                    disabled={generating}
                                >
                                    {generating ? 'Generating...' : 'Generate Invoice'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default SchemeInvoices;
